### PR TITLE
Review required before merge to main: styling resolved, and pulled from main. 

### PR DESCRIPTION
**Pull request by leahkatherine**
Please see my latest commit and let me know if I'm okay to merge to main.

### CODE REVIEW

**Comment by leahkatherine** [comment]
Hi! I found out that once you push for everyone to view, you will have to make a pull request if you want to notify us of your edit and give us more detail as to what you did.  
Screenshot 2023-12-10 180942

**Comment by Benstamous** [comment]
Hi! Don't mind me; I'm just poking around and seeing how to properly work with a pull request on GitHub. Comment test complete!

**Review by Benstamous — APPROVED** [review]
I have reviewed your code and concluded that it won't negativity affect the main branch. I also discovered that removing the sticky property from styles.css won't fix the issue.

You see, styles.css isn't what is connected to index.html; what is connected is styles.la.css. But if styles-la.css has no footer property in it, why is the footer sticky? It turns out that it was Bootstrap! In index.html on line 181, the footer has a class of fixed-bottom. This is Bootstraps way of  applying sticky bottom to the footer. Remove that and problem is solved!

**Comment by leahkatherine** [comment]
Thank you so much for looking in to this Bennie! I went to look at line 181, did some digging on my end and I cant find the class  " fixed-bottom" , could you show my a screen show to see what file your viewing on your end? thank you!

**Comment by Benstamous** [comment]
Check out what I'm seeing on index.html. I made sure to pull from main before looking it over but I'm prone to error.

Screenshot 2023-12-20 215338

**Pull request merged**
